# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('expected', models.IntegerField()),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('periodicity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached', models.IntegerField()),
                ('date', models.DateField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIA.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIA.Project'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIA.User'),
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIA.Project'),
        ),
    ]
