# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='number',
        ),
        migrations.AddField(
            model_name='indicator',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
